#from .essentials import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from BedroomFurnitureMask import BEDROOM_CLASS_MAPPINGS, BEDROOM_DISPLAY_NAME_MAPPINGS


NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(BEDROOM_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BEDROOM_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
